openapi: 3.0.0
info:
  title: Colorado Covid Tracker
  description: API to consume Colorado COVID data
  version: 0.1.0
servers:
  - url: https://okvn4rtq0k.execute-api.us-east-1.amazonaws.com/Prod
    description: API Gateway
paths:
  /data/:
    get:
      summary: Returns all COVID data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/CovidData'
        '403':
          description: Forbidden
components:
  schemas:
    CovidData:
      type: object
      properties:
        data:
          type: object
          properties:
            ave_cases:
              type: array
              items:
                type: object
                properties:
                  death_increase:
                    type: integer
                  hospitalized_currently:
                    type: integer
                  hospitalized_increase:
                    type: integer
                  positive_increase:
                    type: integer
                  reporting_date:
                    type: string
                    format: date
                  tested_increase:
                    type: integer
            ave_vaccines:
              type: array
              items:
                type: object
                properties:
                  daily_qty:
                    type: integer
                  one_dose_increase:
                    type: integer
                  reporting_date:
                    type: string
                    format: date
                  two_doses_increase:
                    type: integer
            daily_cases:
              type: array
              items:
                type: object
                properties:
                  death_confirmed:
                    type: integer
                  death_increase:
                    type: integer
                  hospitalized_currently:
                    type: integer
                  hospitalized_increase:
                    type: integer
                  positive:
                    type: integer
                  positive_increase:
                    type: integer
                  tested:
                    type: integer
                  reporting_date:
                    type: string
                    format: date
                  tested_increase:
                    type: integer
            daily_vaccines:
              type: array
              items:
                type: object
                properties:
                  daily_cumulative:
                    type: integer
                  daily_qty:
                    type: integer
                  one_dose_increase:
                    type: integer
                  one_dose_total:
                    type: integer
                  two_doses_increase:
                    type: integer
                  two_doses_total:
                    type: integer
                  reporting_date:
                    type: string
                    format: date
        last_updated:
          type: string
          format: date-time
