openapi: 3.0.0
info:
  title: Colorado Covid Tracker
  description: API to consume Colorado COVID data
  version: 0.1.0
servers:
  - url: <not hosted yet>
    description: API Gateway
paths:
  /cases_history:
    get:
      summary: Returns a list of covid case and vaccine numbers by day
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/CovidData'
        '405':
          description: Method Not Allowed
          content: 
            'application/json': {}
            'application/xml': {}
components:
  schemas:
    CovidData:
      type: object
      properties:
        date:
          type: string
        newCases:
          type: integer
        cumulativeCases:
          type: integer
        newFirstDoseVaccinated:
          type: integer
        cumulativeFirstDoseVaccinated:
          type: integer
