openapi: 3.0.0
info:
  title: Colorado Covid Tracker
  description: API to consume Colorado covid data
  version: 0.1.0
servers:
  - url: http://staging-api.example.com
    description: API Gateway
paths:
  /cases:
    get:
      summary: Returns a list of covid case numbers by day.
      responses:
        '200':    # status code
          description: A JSON array of covid data
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string