AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  colorado-covid-tracker

  Sample SAM Template for colorado-covid-tracker

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CoCovidFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: app.app
      Runtime: python3.8
      Events:
        CoCovid:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /cases/daily
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CoCovidApi:
    Description: "API Gateway endpoint URL for Prod stage for Colorado Covid function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CoCovidFunction:
    Description: "Colorado Covid Lambda Function ARN"
    Value: !GetAtt CoCovidFunction.Arn
  CoCovidFunctionIamRole:
    Description: "Implicit IAM Role created for Colorado Covid function"
    Value: !GetAtt CoCovidFunctionRole.Arn
