AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  colorado-covid-tracker

  Sample SAM Template for colorado-covid-tracker
Parameters: 
  NotificationEmail:
    Type: String
  DbCredentials:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Database creds in the format postgres://<user>:<pw>@<host>/<db>
    Default: CovidDatabaseURL
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        BUCKET_NAME: !Ref S3Bucket

Resources:
  CoCovidFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/api/
      Handler: app.app
      Runtime: python3.8
      Policies:
      - AmazonS3FullAccess
      - AmazonSSMReadOnlyAccess
      Environment:
        Variables:
          DB_CREDENTIALS: !Ref DbCredentials
      Events:
        Cases:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /cases_history/
            Method: get
        AveCases:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /cases_average/
            Method: get
        Vaccines:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /vaccines_history/
            Method: get
        AveVaccines:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /vaccines_average/
            Method: get
  
  RawDailyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/etl/
      Handler: extract.handler
      Runtime: python3.8
      Policies:
      - AmazonS3FullAccess
      - AmazonSSMReadOnlyAccess
      Events:
        EEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 3 * * ? *)

  TransformDailyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/etl/
      Handler: transform.handler
      Runtime: python3.8
      Policies:
      - AmazonS3FullAccess
      - AmazonSSMReadOnlyAccess
      Events:
        TEvent:
          Type: Schedule
          Properties:
            Schedule: cron(2 3 * * ? *)

  LoadDailyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/etl/
      Handler: load.handler
      Runtime: python3.8
      Policies:
      - AmazonS3FullAccess
      - AmazonSSMReadOnlyAccess
      Environment:
        Variables:
          DB_CREDENTIALS: !Ref DbCredentials
      Events:
        LEvent:
          Type: Schedule
          Properties:
            Schedule: cron(4 3 * * ? *)

  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: email
        Endpoint: !Ref NotificationEmail

  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: APIFunction
          Value: !Ref CoCovidFunction
        - Name: RawLambdaFunction
          Value: !Ref RawDailyFunction
        - Name: TransormLambdaFunction
          Value: !Ref TransformDailyFunction
        - Name: LoadLambdaFunction
          Value: !Ref LoadDailyFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: '1'

  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

Outputs:
  CoCovidApi:
    Description: "API Gateway endpoint URL for Prod stage for Colorado Covid function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cases_history/"
  CoCovidFunction:
    Description: "Colorado Covid Lambda Function ARN"
    Value: !GetAtt CoCovidFunction.Arn
  CoCovidFunctionIamRole:
    Description: "Implicit IAM Role created for Colorado Covid function"
    Value: !GetAtt CoCovidFunctionRole.Arn
