AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  colorado-covid-tracker

  Sample SAM Template for colorado-covid-tracker
Parameters: 
  NotificationEmail:
    Type: String
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        BUCKET_NAME: !Ref S3Bucket

Resources:
  CoCovidFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/api/
      Handler: app.app
      Runtime: python3.8
      Events:
        CoCovid:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /covid-data
            Method: get
  
  ExtractRawDataDailyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/etl/
      Handler: extract_raw_data.handler
      Runtime: runtime
      Events:
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(15 10 * * ? *)

  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: email
        Endpoint: !Ref NotificationEmail

  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ExtractRawDataDailyFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: '1'

  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

Outputs:
  CoCovidApi:
    Description: "API Gateway endpoint URL for Prod stage for Colorado Covid function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/covid-data/"
  CoCovidFunction:
    Description: "Colorado Covid Lambda Function ARN"
    Value: !GetAtt CoCovidFunction.Arn
  CoCovidFunctionIamRole:
    Description: "Implicit IAM Role created for Colorado Covid function"
    Value: !GetAtt CoCovidFunctionRole.Arn
